// <auto-generated />
using System;
using Footbally_Infrastructure.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Footbally_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610101347_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Footbally_Domain.Entities.MatchEntity.Entity.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayGoals")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("Footbally_Domain.Entities.PlayerEntity.Entity.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(14);

                    b.Property<int>("Assist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Goals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ShirtNumber")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Footbally_Domain.Entities.StandingEntity.Entity.Standing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Lost")
                        .HasColumnType("int");

                    b.Property<int>("Played")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Won")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("Footbally_Domain.Entities.TeamEntity.Entity.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachName = "Lionel Scaloni",
                            Country = "Argentina",
                            GroupNumber = 10
                        },
                        new
                        {
                            Id = 2,
                            CoachName = "Carlo Ancelotti",
                            Country = "Brazil",
                            GroupNumber = 3
                        },
                        new
                        {
                            Id = 3,
                            CoachName = "Thomas Tuchel",
                            Country = "England",
                            GroupNumber = 12
                        },
                        new
                        {
                            Id = 4,
                            CoachName = "Didier Deschamps",
                            Country = "France",
                            GroupNumber = 9
                        },
                        new
                        {
                            Id = 5,
                            CoachName = "Julian Nagelsmann",
                            Country = "Germany",
                            GroupNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            CoachName = "Luis de la Fuente",
                            Country = "Spain",
                            GroupNumber = 8
                        },
                        new
                        {
                            Id = 7,
                            CoachName = "Roberto Martinez",
                            Country = "Portugal",
                            GroupNumber = 11
                        },
                        new
                        {
                            Id = 8,
                            CoachName = "Rudi Garcia",
                            Country = "Belgium",
                            GroupNumber = 7
                        },
                        new
                        {
                            Id = 9,
                            CoachName = "Ronald Koeman",
                            Country = "Netherlands",
                            GroupNumber = 6
                        },
                        new
                        {
                            Id = 10,
                            CoachName = "Zlatko Dalic",
                            Country = "Croatia",
                            GroupNumber = 12
                        },
                        new
                        {
                            Id = 11,
                            CoachName = "Murat Yakin",
                            Country = "Switzerland",
                            GroupNumber = 2
                        },
                        new
                        {
                            Id = 12,
                            CoachName = "Ralf Rangnick",
                            Country = "Austria",
                            GroupNumber = 10
                        },
                        new
                        {
                            Id = 13,
                            CoachName = "Graham Potter",
                            Country = "Sweden",
                            GroupNumber = 6
                        },
                        new
                        {
                            Id = 14,
                            CoachName = "Stale Solbakken",
                            Country = "Norway",
                            GroupNumber = 9
                        },
                        new
                        {
                            Id = 15,
                            CoachName = "Steve Clarke",
                            Country = "Scotland",
                            GroupNumber = 3
                        },
                        new
                        {
                            Id = 16,
                            CoachName = "Sergej Barbarez",
                            Country = "Bosnia and Herzegovina",
                            GroupNumber = 2
                        },
                        new
                        {
                            Id = 17,
                            CoachName = "Miroslav Koubek",
                            Country = "Czechia",
                            GroupNumber = 1
                        },
                        new
                        {
                            Id = 18,
                            CoachName = "Vincenzo Montella",
                            Country = "Turkey",
                            GroupNumber = 4
                        },
                        new
                        {
                            Id = 19,
                            CoachName = "Javier Aguirre",
                            Country = "Mexico",
                            GroupNumber = 1
                        },
                        new
                        {
                            Id = 20,
                            CoachName = "Jesse Marsch",
                            Country = "Canada",
                            GroupNumber = 2
                        },
                        new
                        {
                            Id = 21,
                            CoachName = "Mauricio Pochettino",
                            Country = "USA",
                            GroupNumber = 4
                        },
                        new
                        {
                            Id = 22,
                            CoachName = "Thomas Christiansen",
                            Country = "Panama",
                            GroupNumber = 12
                        },
                        new
                        {
                            Id = 23,
                            CoachName = "Dick Advocaat",
                            Country = "Curacao",
                            GroupNumber = 5
                        },
                        new
                        {
                            Id = 24,
                            CoachName = "Sebastien Migne",
                            Country = "Haiti",
                            GroupNumber = 3
                        },
                        new
                        {
                            Id = 25,
                            CoachName = "Hajime Moriyasu",
                            Country = "Japan",
                            GroupNumber = 6
                        },
                        new
                        {
                            Id = 26,
                            CoachName = "Hong Myung-bo",
                            Country = "South Korea",
                            GroupNumber = 1
                        },
                        new
                        {
                            Id = 27,
                            CoachName = "Amir Ghalenoei",
                            Country = "Iran",
                            GroupNumber = 7
                        },
                        new
                        {
                            Id = 28,
                            CoachName = "Tony Popovic",
                            Country = "Australia",
                            GroupNumber = 4
                        },
                        new
                        {
                            Id = 29,
                            CoachName = "Georgios Donis",
                            Country = "Saudi Arabia",
                            GroupNumber = 8
                        },
                        new
                        {
                            Id = 30,
                            CoachName = "Julen Lopetegui",
                            Country = "Qatar",
                            GroupNumber = 2
                        },
                        new
                        {
                            Id = 31,
                            CoachName = "Fabio Cannavaro",
                            Country = "Uzbekistan",
                            GroupNumber = 11
                        },
                        new
                        {
                            Id = 32,
                            CoachName = "Jamal Sellami",
                            Country = "Jordan",
                            GroupNumber = 10
                        },
                        new
                        {
                            Id = 33,
                            CoachName = "Graham Arnold",
                            Country = "Iraq",
                            GroupNumber = 9
                        },
                        new
                        {
                            Id = 34,
                            CoachName = "Mohamed Ouahbi",
                            Country = "Morocco",
                            GroupNumber = 3
                        },
                        new
                        {
                            Id = 35,
                            CoachName = "Pape Thiaw",
                            Country = "Senegal",
                            GroupNumber = 9
                        },
                        new
                        {
                            Id = 36,
                            CoachName = "Hossam Hassan",
                            Country = "Egypt",
                            GroupNumber = 7
                        },
                        new
                        {
                            Id = 37,
                            CoachName = "Vladimir Petkovic",
                            Country = "Algeria",
                            GroupNumber = 10
                        },
                        new
                        {
                            Id = 38,
                            CoachName = "Hugo Broos",
                            Country = "South Africa",
                            GroupNumber = 1
                        },
                        new
                        {
                            Id = 39,
                            CoachName = "Carlos Queiroz",
                            Country = "Ghana",
                            GroupNumber = 12
                        },
                        new
                        {
                            Id = 40,
                            CoachName = "Sabri Lamouchi",
                            Country = "Tunisia",
                            GroupNumber = 6
                        },
                        new
                        {
                            Id = 41,
                            CoachName = "Emerse Fae",
                            Country = "Ivory Coast",
                            GroupNumber = 5
                        },
                        new
                        {
                            Id = 42,
                            CoachName = "Sebastien Desabre",
                            Country = "DR Congo",
                            GroupNumber = 11
                        },
                        new
                        {
                            Id = 43,
                            CoachName = "Bubista",
                            Country = "Cape Verde",
                            GroupNumber = 8
                        },
                        new
                        {
                            Id = 44,
                            CoachName = "Lionel Scaloni",
                            Country = "Argentina",
                            GroupNumber = 10
                        },
                        new
                        {
                            Id = 45,
                            CoachName = "Marcelo Bielsa",
                            Country = "Uruguay",
                            GroupNumber = 8
                        },
                        new
                        {
                            Id = 46,
                            CoachName = "Nestor Lorenzo",
                            Country = "Colombia",
                            GroupNumber = 11
                        },
                        new
                        {
                            Id = 47,
                            CoachName = "Sebastian Beccacece",
                            Country = "Ecuador",
                            GroupNumber = 5
                        },
                        new
                        {
                            Id = 48,
                            CoachName = "Gustavo Alfaro",
                            Country = "Paraguay",
                            GroupNumber = 4
                        });
                });

            modelBuilder.Entity("Footbally_Domain.Entities.MatchEntity.Entity.Match", b =>
                {
                    b.HasOne("Footbally_Domain.Entities.TeamEntity.Entity.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Footbally_Domain.Entities.TeamEntity.Entity.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("Footbally_Domain.Entities.PlayerEntity.Entity.Player", b =>
                {
                    b.HasOne("Footbally_Domain.Entities.TeamEntity.Entity.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Footbally_Domain.Entities.StandingEntity.Entity.Standing", b =>
                {
                    b.HasOne("Footbally_Domain.Entities.TeamEntity.Entity.Team", null)
                        .WithOne("Standing")
                        .HasForeignKey("Footbally_Domain.Entities.StandingEntity.Entity.Standing", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Footbally_Domain.Entities.TeamEntity.Entity.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");

                    b.Navigation("Standing")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
